### ISSUE TITLE
Access to GitHub Package Registry no possible

### ISSUE THREAD

**Issue by mzuehlke** [igor-vovk/cats-effect-simple-di#10]
Thanks for transferring the code from your article into a library.

I added to my `build.sbt` the resolver as shown in the Readme:
```Scala
ThisBuild / resolvers += "GitHub Package Registry (igor-vovk)" at "https://maven.pkg.github.com/igor-vovk/_"
```

But when trying to downloading from that package repository `sbt` throws an error:
```bash
[warn] 	Note: Unresolved dependencies path:
[error] stack trace is suppressed; run 'last app / update' for the full output
[error] (app / update) sbt.librarymanagement.ResolveException: Error downloading io.github.igor-vovk:cats-effect-simple-di_3:0.1.1
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/io/github/igor-vovk/cats-effect-simple-di_3/0.1.1/cats-effect-simple-di_3-0.1.1.pom
[error]   unauthorized: https://maven.pkg.github.com/igor-vovk/_/io/github/igor-vovk/cats-effect-simple-di_3/0.1.1/cats-effect-simple-di_3-0.1.1.pom (GitHub Package Registry)
```

Are the Github package repos not general accessible ?

**Comment by igor-vovk** [comment]
Hi! That is indeed very strange. I've created a new project with this build.sbt contents:
```
ThisBuild / version := "0.1.0-SNAPSHOT"

ThisBuild / scalaVersion := "3.3.3"

ThisBuild / resolvers += "GitHub Package Registry (igor-vovk)" at "https://maven.pkg.github.com/igor-vovk/_"

lazy val root = (project in file("."))
  .settings(
    name := "SbtGithubTest",
    libraryDependencies += "io.github.igor-vovk" %% "cats-effect-simple-di" % "0.1.1"
  )
```
, and it worked for me. I couldn't find any specific auth setting on my computer, that would intervene. Could you please create a fresh project with this `build.sbt` contents and see if it works?

**Comment by igor-vovk** [comment]
Apart from that, I want to publish it to the Maven Central so there will be no need to add specific repo resolver, but couldn't because of the braking changes in Sonatype Central that require new projects to be published slightly differently (https://github.com/sbt/sbt-ci-release/issues/294). I'll try to revisit it when it will be fixed.

**Comment by mzuehlke** [comment]
With the simple project I get the same error 😢 
Maybe you define in some global config a Github access token.

https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility#about-setting-visibility-and-access-permissions-for-packages

> In most registries, to pull a package, you must authenticate with a personal access token or `GITHUB_TOKEN`, regardless of whether the package is public or private. However, in the Container registry, public packages allow anonymous access and can be pulled without authentication or signing in via the CLI.

**Comment by igor-vovk** [comment]
Thank you for pointing it out. My idea was, that if `GITHUB_TOKEN` is omitted it will only rate limit more aggressively. 

I will try to publish the package to the Sonatype Central once more, but meanwhile unfortunately that means the library is not accessible without providing the token.

**Comment by igor-vovk** [comment]
Hi! You can now use version `0.1.3`, which was published to Sonatype Central. Also updated the docs to reflect it.

**Comment by mzuehlke** [comment]
I confirmed, it is now working. 
Thanks for the effort.
